version: "3.8"

services:
  guiomar:
    build: .
    ports:
      - "7777:7777"
    links:
      - guiomar-db
    depends_on: 
      - guiomar-db
    environment:
      - NEO4J_HOST=bolt://guiomar-db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=carmel

  guiomar-db:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/carmel

volumes:
  neo4j_data:
  neo4j_logs: