definitions:
  chef.createChefPayload:
    properties:
      email:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  food.createFoodPayload:
    properties:
      family:
        type: string
      genus:
        type: string
      name:
        type: string
      order:
        type: string
      scientific_name:
        type: string
      specie:
        type: string
    type: object
  ingredient.IngredientPayload:
    properties:
      amount: {}
      food: {}
    type: object
  recipe.createRecipePayload:
    properties:
      cook_duration:
        type: number
      directions:
        items:
          $ref: '#/definitions/step.StepPayload'
        type: array
      ingredients:
        items:
          $ref: '#/definitions/ingredient.IngredientPayload'
        type: array
      introduction:
        type: string
      preparation_time:
        type: number
      serving:
        type: number
      summary:
        type: string
      yield:
        type: number
    type: object
  step.StepPayload:
    properties:
      description:
        type: string
      duration:
        type: number
    type: object
host: localhost:7777
info:
  contact:
    email: mematheuslc@gmail.com
    name: Matheus Carmo
    url: http://www.swagger.io/support
  description: Guiomar private and public API docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Guiomar API
  version: "1.0"
paths:
  /api/chefs:
    post:
      consumes:
      - application/json
      description: You just need your name and your e-mail
      parameters:
      - description: Create a new chef
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/chef.createChefPayload'
      produces:
      - application/json
      responses: {}
      summary: Create a new chef
      tags:
      - chef
  /api/foods:
    post:
      consumes:
      - application/json
      description: Creates a new food which can be used within recipes
      parameters:
      - description: Create a new food
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/food.createFoodPayload'
      produces:
      - application/json
      responses: {}
      summary: Create a new food
      tags:
      - food
  /api/recipes:
    post:
      consumes:
      - application/json
      description: You just need your name and your e-mail
      parameters:
      - description: Create a new recipe
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/recipe.createRecipePayload'
      produces:
      - application/json
      responses: {}
      summary: Create a new recipe
      tags:
      - chef
swagger: "2.0"
