definitions:
  basket.basketPayload:
    properties:
      recipes:
        items:
          type: string
        type: array
    type: object
  chef.createChefPayload:
    properties:
      email:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  food.FindFoodPayload:
    properties:
      id:
        type: string
      type:
        type: string
    type: object
  food.createFoodPayload:
    properties:
      animal_type:
        type: string
      average_amount:
        $ref: '#/definitions/measurements.UnitType'
      family:
        type: string
      genus:
        type: string
      name:
        type: string
      order:
        type: string
      scientific_name:
        type: string
      specie:
        type: string
      type:
        type: string
    type: object
  ingredient.IngredientPayload:
    properties:
      amount:
        $ref: '#/definitions/measurements.UnitType'
      food:
        $ref: '#/definitions/food.FindFoodPayload'
    type: object
  measurements.UnitType:
    properties:
      type:
        type: string
      value:
        type: number
    type: object
  recipe.createRecipePayload:
    properties:
      cook_duration:
        type: integer
      directions:
        items:
          $ref: '#/definitions/step.StepPayload'
        type: array
      ingredients:
        items:
          $ref: '#/definitions/ingredient.IngredientPayload'
        type: array
      introduction:
        type: string
      preparation_time:
        $ref: '#/definitions/time.Duration'
      serving:
        type: integer
      summary:
        type: string
      yield:
        type: integer
    type: object
  step.StepPayload:
    properties:
      description:
        type: string
      duration:
        type: integer
    type: object
  time.Duration:
    enum:
    - 1
    - 1000
    - 1000000
    - 1000000000
    - 60000000000
    - 3600000000000
    type: integer
    x-enum-varnames:
    - Nanosecond
    - Microsecond
    - Millisecond
    - Second
    - Minute
    - Hour
host: localhost:3010
info:
  contact:
    email: mematheuslc@gmail.com
    name: Matheus Carmo
    url: http://www.swagger.io/support
  description: Guiomar private and public API docs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Guiomar API
  version: "1.0"
paths:
  /api/basket:
    post:
      consumes:
      - application/json
      description: List the recipes you want
      parameters:
      - description: create a new basket based on some payload
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/basket.basketPayload'
      produces:
      - application/json
      responses: {}
      summary: Create a new basket based on many recipes
      tags:
      - basket
  /api/chefs:
    post:
      consumes:
      - application/json
      description: You just need your name and your e-mail
      parameters:
      - description: Create a new chef
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/chef.createChefPayload'
      produces:
      - application/json
      responses: {}
      summary: Create a new chef
      tags:
      - chef
  /api/foods:
    post:
      consumes:
      - application/json
      description: Creates a new food which can be used within recipes
      parameters:
      - description: Create a new food
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/food.createFoodPayload'
      produces:
      - application/json
      responses: {}
      summary: Create a new food
      tags:
      - food
  /api/recipes:
    post:
      consumes:
      - application/json
      description: You just need your name and your e-mail
      parameters:
      - description: Create a new recipe
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/recipe.createRecipePayload'
      produces:
      - application/json
      responses: {}
      summary: Create a new recipe
      tags:
      - chef
swagger: "2.0"
